apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.label }}
  labels:
    run: {{ .Values.label }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.exposePort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    run: {{ .Values.label }}