# Default values for blueonion.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
label: user-management
exposePort: 8000
namespace: user-management

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: LoadBalancer
  port: 80
  protocol: TCP

resources:
  requests:
    memory: "200Mi"
    cpu: "200m"
  limits:
    memory: "250Mi"
    cpu: "250m"
